### PR TITLE
DM-34465: Add nanojansky photometry UDFs

### PR DESCRIPTION
**Pull request by fritzm**
This adds `nanojanskyToAbMag`, `nanojanksyToAbMagSigma`, `abMagToNanojansky` and `abMagToNanojanskySigma`.

Some small Python compatos and warns were also addressed, as well as one oddity with MariaDB version string in the official MariaDB docker containers not being quite of the form expected by some of the deploy/undeploy tooling.

Some unit tests were added, and threw in some for the previously uncovered cgs flux <-> AB mag UDFs as a bonus, since they are so similar in structure.

### CODE REVIEW

**Review by smonkewitz — APPROVED** [review]
Looks good to me - thanks for the tests!

Side note - should we think about changing the copyright to something like "the SciSQL authors"?

**Comment by fritzm** [comment]
Thanks, Serge.

Re. copyright -- sure!  I can do this on an upcoming PR.  I was thinking I'd tackle the TODO of refreshing the README also.

**Comment by gpdf** [comment]
@fritzm @smonkewitz Presumably we need a new release now?  Also, is there a release-notes file anywhere in the code base?

**Comment by fritzm** [comment]
Yup -- I think everything I want to get in there for next release is up on PR now.  I'll go add a release notes file rn to one of the open PRs.  Thanks for finding the time for these reviews, @smonkewitz!

**Pull request merged**
